# Generated by Django 5.2.4 on 2025-07-08 00:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_criar_usuarios_iniciais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Esporte',
                'verbose_name_plural': 'Esportes',
            },
        ),
        migrations.CreateModel(
            name='Escola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('tipo', models.CharField(max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='escolas/logos/')),
                ('responsavel', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escolas_responsavel', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Escola',
                'verbose_name_plural': 'Escolas',
            },
        ),
        migrations.CreateModel(
            name='AlunoEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='alunos/fotos/')),
                ('status', models.CharField(choices=[('ALUNO', 'Aluno'), ('SOCIO', 'Sócio'), ('ALUNO_SOCIO', 'Aluno/Sócio')], default='ALUNO', max_length=20)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alunos_escola', to='club.socio')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alunos', to='club.escola')),
            ],
            options={
                'verbose_name': 'Aluno de Escola',
                'verbose_name_plural': 'Alunos de Escola',
            },
        ),
        migrations.CreateModel(
            name='FinanceiroEscola',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('data_pagamento', models.DateField()),
                ('observacao', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='club.alunoescola')),
                ('escola', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='financeiro', to='club.escola')),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagamentos', to='club.esporte')),
            ],
            options={
                'verbose_name': 'Financeiro da Escola',
                'verbose_name_plural': 'Financeiro das Escolas',
            },
        ),
        migrations.CreateModel(
            name='HorarioEsporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.CharField(max_length=20)),
                ('horario', models.TimeField()),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, max_digits=8)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='club.alunoescola')),
                ('esporte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='horarios', to='club.esporte')),
            ],
            options={
                'verbose_name': 'Horário de Esporte',
                'verbose_name_plural': 'Horários de Esporte',
            },
        ),
        migrations.AddField(
            model_name='alunoescola',
            name='esportes',
            field=models.ManyToManyField(related_name='alunos', through='club.HorarioEsporte', to='club.esporte'),
        ),
    ]
