# Generated by Django 5.2.4 on 2025-07-08 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_esporte_escola_alunoescola_financeiroescola_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracaoIntegracaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(choices=[('GERENCIANET', 'Gerencianet'), ('ASAAS', 'Asaas'), ('OUTRO', 'Outro')], default='GERENCIANET', max_length=30)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('webhook_url', models.URLField(blank=True)),
                ('ambiente', models.CharField(choices=[('PRODUCAO', 'Produção'), ('HOMOLOGACAO', 'Homologação')], default='HOMOLOGACAO', max_length=20)),
                ('ativo', models.BooleanField(default=True)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuração Integração Financeira',
                'verbose_name_plural': 'Configurações Integração Financeira',
            },
        ),
        migrations.CreateModel(
            name='Cobranca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('vencimento', models.DateField()),
                ('status', models.CharField(choices=[('PENDENTE', 'Pendente'), ('PAGO', 'Pago'), ('CANCELADO', 'Cancelado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('linha_digitavel', models.CharField(blank=True, max_length=255)),
                ('nosso_numero', models.CharField(blank=True, max_length=50)),
                ('codigo_barras', models.CharField(blank=True, max_length=255)),
                ('data_emissao', models.DateTimeField(auto_now_add=True)),
                ('data_baixa', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.TextField(blank=True)),
                ('retorno_banco', models.TextField(blank=True)),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas', to='club.alunoescola')),
            ],
            options={
                'verbose_name': 'Cobrança',
                'verbose_name_plural': 'Cobranças',
            },
        ),
    ]
