# Generated by Django 5.2.4 on 2025-07-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_configuracaointegracaofinanceira_cobranca'),
    ]

    operations = [
        migrations.AddField(
            model_name='esporte',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='esportes_logos/'),
        ),
        migrations.AddField(
            model_name='esporte',
            name='tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
