# Generated by Django 5.2.4 on 2025-07-08 18:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("club", "0005_esporte_logo_esporte_tipo"),
    ]

    operations = [
        migrations.CreateModel(
            name="CategoriaFinanceira",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=100)),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("RECEITA", "Receita"),
                            ("DESPESA", "Despesa"),
                            ("TRANSFERENCIA", "Transferência"),
                        ],
                        max_length=15,
                    ),
                ),
                ("ativa", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Categoria Financeira",
                "verbose_name_plural": "Categorias Financeiras",
            },
        ),
        migrations.CreateModel(
            name="ClienteDayUse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("frequencia", models.PositiveIntegerField(default=0)),
                ("preferencias", models.CharField(blank=True, max_length=255)),
                (
                    "valor_gasto",
                    models.DecimalField(decimal_places=2, default=0, max_digits=8),
                ),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="club.cliente",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente Day-Use",
                "verbose_name_plural": "Clientes Day-Use",
            },
        ),
        migrations.CreateModel(
            name="ClienteLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("modalidade", models.CharField(max_length=100)),
                ("potencial_conversao", models.BooleanField(default=False)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="club.cliente",
                    ),
                ),
                (
                    "escola",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="club.escolaesporte",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente Lead",
                "verbose_name_plural": "Clientes Lead",
            },
        ),
        migrations.CreateModel(
            name="ClienteLocador",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tipo_evento", models.CharField(max_length=100)),
                ("data_criacao", models.DateTimeField(auto_now_add=True)),
                (
                    "cliente",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="club.cliente",
                    ),
                ),
                (
                    "espaco_preferido",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="club.espaco",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cliente Locador",
                "verbose_name_plural": "Clientes Locadores",
            },
        ),
        migrations.CreateModel(
            name="LancamentoFinanceiro",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("data", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("descricao", models.CharField(blank=True, max_length=255)),
                ("conciliado", models.BooleanField(default=False)),
                ("data_conciliacao", models.DateField(blank=True, null=True)),
                ("observacoes", models.TextField(blank=True, null=True)),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "categoria",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club.categoriafinanceira",
                    ),
                ),
                (
                    "conta",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="club.contabancaria",
                    ),
                ),
                (
                    "usuario",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Lançamento Financeiro",
                "verbose_name_plural": "Lançamentos Financeiros",
                "ordering": ["-data", "-criado_em"],
            },
        ),
    ]
